sudo: required
dist: trusty

services:
  - mongodb
env:
  global:
    secure: HELJx6WPr+W2S0FV47KkRdlS9NCqlMcdRMK8xWgRqqrEPv24KEvNnHxCy0tRbzITqadYtyvI1MtqtmpG04uty8Gpkc7w6L6LMJ/OuLG0gVX7AnaUovYTlY04m1/L9oyzOrTDXk5J/BKbcyiz7uJtkTc/A8MMZAFfZh7hmhLID78= # BUILD_TRIGGER_URL

install:
  - bin/install-ubuntu.sh
  - test/bin/setup-integration-tests-ubuntu.sh

script:
  - SCITRAN_PERSISTENT_DB_PORT=27017 test/bin/run-tests-ubuntu.sh

after_success:
  - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
      # upload my python reports
      bash <(curl -s https://codecov.io/bash) -cF python
  fi

  
